# Generated by Django 5.0.1 on 2024-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_border_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='border_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
