# Generated by Django 5.0.1 on 2024-01-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_border_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='border_color',
        ),
    ]
