# Generated by Django 5.0.1 on 2024-01-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
