# Generated by Django 5.0.1 on 2024-01-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_operator_color_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='color_column',
            field=models.CharField(default='#FFFFFF', max_length=255, null=True),
        ),
    ]
